services:

  management-console:
    container_name: management-console
    image: docker.io/apache/incubator-kie-kogito-management-console:10.0.0
    ports:
      - 8280:8080
    volumes:
      - ./svg/:/home/kogito/data/svg/
    environment:
      KOGITO_DATAINDEX_HTTP_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8080/graphql
      KOGITO_MANAGEMENT_CONSOLE_PROPS: -Dkogito.svg.folder.path=/home/kogito/data/svg
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"