version: '3.8'

services:
  pflege-prozess-kogito:
    image: ghcr.io/thi-projekte/pflege/pflege-prozess:latest
    ports:
      - "8081:8080"
    networks:
      - nginx-proxy-manager
    volumes:
      - ./pdf-exports:/opt/app/pdfs  

networks:
  nginx-proxy-manager:
    external: true
