name: Build and Push to GHCR

on:
  push:
    paths:
      - 'homepage/pflegital/**'
      - 'homepage/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/projektpflegital/homepage:latest
        docker build -t $IMAGE_NAME .
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME