name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and analyze Chatbot
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: chatbot
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=thi-projekte_chatbot

      - name: Build and analyze Pflege-Prozess
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: pflege-prozess
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=thi-projekte_pflege_prozess