name: Build, Push and Redeploy Container via Portainer API

on:
  push:
    paths:
      - 'homepage/pflegital/**'
      - 'homepage/Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build-and-redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/thi-projekte/pflege/homepage:latest
          docker build -f homepage/Dockerfile -t $IMAGE homepage
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push $IMAGE

      - name: Redeploy Container via Portainer API
        env:
          API_URL: https://winfprojekt.de:9443/api
          API_KEY: ${{ secrets.PORTAINER_API_KEY }}
          ENDPOINT_ID: 1
          # Der Präfix deines Compose-Stacks + Service-Name:
          CONTAINER_FILTER: pflegital-homepage
        run: |
          # 1. Container-ID ermitteln (matcht 'pflegital-homepage-1')
          CONTAINER_ID=$(curl -k -s -H "X-API-Key: $API_KEY" \
            "$API_URL/endpoints/$ENDPOINT_ID/docker/containers/json" \
            | jq -r ".[] | select(.Names[] | contains(\"$CONTAINER_FILTER\")) | .Id")

          if [ -z "$CONTAINER_ID" ]; then
            echo "❌ Container mit Filter '$CONTAINER_FILTER' nicht gefunden!"
            exit 1
          fi
          echo "▶️ Found container ID: $CONTAINER_ID"

          # 2. Neuestes Image pullen
          echo "⬇️ Pull latest image $IMAGE"
          curl -k -X POST -H "X-API-Key: $API_KEY" \
            "$API_URL/endpoints/$ENDPOINT_ID/docker/images/create?fromImage=$IMAGE&tag=latest"

          # 3. Alten Container stoppen
          echo "⏸️ Stop container $CONTAINER_ID"
          curl -k -X POST -H "X-API-Key: $API_KEY" \
            "$API_URL/endpoints/$ENDPOINT_ID/docker/containers/$CONTAINER_ID/stop"

          # 4. Alten Container entfernen
          echo "🗑️ Remove container $CONTAINER_ID"
          curl -k -X DELETE -H "X-API-Key: $API_KEY" \
            "$API_URL/endpoints/$ENDPOINT_ID/docker/containers/$CONTAINER_ID"

          # 5. Neuen Container mit latest Image erstellen
          echo "🔄 Create new container with name filter '$CONTAINER_FILTER'"
          curl -k -X POST -H "X-API-Key: $API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
                  "Image": "'"$IMAGE"'",
                  "name": "'"$CONTAINER_FILTER"-1"'",
                  "HostConfig": {
                    "NetworkMode": "nginx-proxy-manager",
                    "RestartPolicy": { "Name": "always" }
                  }
                }' \
            "$API_URL/endpoints/$ENDPOINT_ID/docker/containers/create?name=$CONTAINER_FILTER-1"

          # 6. Neuen Container starten
          echo "▶️ Start new container '$CONTAINER_FILTER-1'"
          curl -k -X POST -H "X-API-Key: $API_KEY" \
            "$API_URL/endpoints/$ENDPOINT_ID/docker/containers/$CONTAINER_FILTER-1/start"

          echo "✅ Redeploy abgeschlossen!"
