name: Website CI/CD using Portainer API

on:
  push:
    paths:
      - 'homepage/pflegital/**'
      - 'homepage/Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/thi-projekte/pflege/homepage:latest
          docker build -f homepage/Dockerfile -t $IMAGE_NAME homepage
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME

      - name: Update Container via Portainer API
        env:
          API_URL: https://portainer.winfprojekt.de
          API_TOKEN: ${{ secrets.PORTAINER_API_KEY }}
        run: |
          CONTAINER_NAME="homepage"

          # Hole die Container-ID
          CONTAINER_ID=$(curl -s -H "Authorization: Bearer $API_TOKEN" "$API_URL/endpoints/1/docker/containers/json" | jq -r ".[] | select(.Names[] | contains(\"${CONTAINER_NAME}\")) | .Id")

          if [ -z "$CONTAINER_ID" ]; then
            echo "Container not found!"
            exit 1
          fi

          echo "Updating container: $CONTAINER_ID"

          # Neustart des Containers
          curl -X POST -H "Authorization: Bearer $API_TOKEN" \
               "$API_URL/endpoints/1/docker/containers/$CONTAINER_ID/update" \
               -d '{"RestartPolicy": {"Name": "always"}}'

          # Image neu pullen
          curl -X POST -H "Authorization: Bearer $API_TOKEN" \
               "$API_URL/endpoints/1/docker/images/create?fromImage=ghcr.io/thi-projekte/pflege/homepage&tag=latest"

          # Container neu starten
          curl -X POST -H "Authorization: Bearer $API_TOKEN" \
               "$API_URL/endpoints/1/docker/containers/$CONTAINER_ID/restart"
