name: Build, Push and Redeploy via Portainer API

on:
  push:
    paths:
      - 'homepage/pflegital/**'
      - 'homepage/Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build-and-redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/thi-projekte/pflege/homepage:latest
          docker build -f homepage/Dockerfile -t $IMAGE homepage
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push $IMAGE

      - name: Redeploy Portainer Stack
        env:
          API_KEY: ${{ secrets.PORTAINER_API_KEY }}
        run: |
          curl -k -X PUT \
            -H "X-API-Key: $API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"StackFileContent\":\"version: '3.8'\\nservices:\\n  homepage:\\n    image: ghcr.io/thi-projekte/pflege/homepage:latest\\n    restart: unless-stopped\\n    networks:\\n      - nginx-proxy-manager\\nnetworks:\\n  nginx-proxy-manager:\\n    external: true\"}" \
            "https://winfprojekt.de:9443/api/stacks/67?endpointId=1"
