name: Pflegital Homepage CI/CD

on:
  push:
    paths:
      - 'homepage/pflegital/**'
      - 'homepage/Dockerfile'

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -f homepage/Dockerfile \
            -t ghcr.io/thi-projekte/pflege/homepage:latest homepage

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/thi-projekte/pflege/homepage:latest
